name: DEMO2
on: [push]
jobs:
  new-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-gitrepo
        uses: actions/checkout@v4.1.1
      - name: dockerlogin 
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}
      - name: imagebuild
        run: docker build -t ramalkshmi79/demo:demo2-image
      - name: pushing
        run: docker push ramalakshmi79/demo:demo2-image
