# name: Hello World Workflow
# on: [push]
# jobs:
#   hello_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4.1.1
#       - name: Say Hello
#         run: echo "Hello, World!"
#       # - name: dockerlogin
#       #   run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_TOKEN }}
#       # - name: dockerbuild
#       #   run: docker build -t ramalakshmi79/demo:nginx-workflow .
#       # - name: dockerimage-push
#       #   run: docker push ramalakshmi79/demo:nginx-workflow
#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           push: true
#           tags: ramalakshmi79/demo:nginx-workflow
