name: Demo3anu
on: push
jobs: 
  anujob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: dockerhub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}
      - name: imagebuild
        run: docker build -t ramalakshmi79/demo:anu .
      - name: pushing image
        run: docker push ramalakshmi79/demo:anu
