name: Demo3anu
on: push
jobs: 
  anujob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: dockerhub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}
      - name: imagebuild
        run: docker build -t ramalakshmi79/demo:anu .
      - name: pushing image
        run: docker push ramalakshmi79/demo:anu
      - name: ec2connect
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PEMKEY }}
          HOSTNAME: ${{secrets.EC2_HOSTNAME}}
          USER_NAME: ${{secrets.EC2_USERNAME}} 
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            docker pull ramalakshmi79/demo:anu
            docker run -d -p 880:80 ramalakshmi79/demo:anu
            '


 


         


