name: Newwork-task3new
on: [push]
jobs:
  CI_CD_PIPELINE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Dockerhublogin
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with: 
          push: true
          tags: ramalakshmi79/demo:newnginx-image
      - name: Ec2 connect
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PEMKEY }}
          HOSTNAME: ${{secrets.EC2_HOSTNAME}}
          USER_NAME: ${{secrets.EC2_USERNAME}}
        run: |
         echo "$PRIVATE_KEY" > private_key.pem 
         chmod 400 private_key.pem
         cat private_key.pem
         ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            sudo docker login -u ramalakshmi79 -p dckr_pat_nU7IyOT8C6mnnwOH9KNS9_Wi4IY
            sudo docker pull  ramalakshmi79/demo:newnginx-image
            sudo docker run -d -p 80:80 ramalakshmi79/demo:newnginx-image
            '
