# name: Newwork-task3
# on: [push]
# jobs:
#   CI-CD_PIPELINE:
#     runs-on: ubuntu:latest
#     steps:
#       - name: Checkout
#         uses: action/checkout@v4.1.4
#       - name: Dockerhublogin
#         uses: docker/login-action@v3
#         with:
#           username: ${{secrets.DOCKER_USERNAME}}
#           password: ${{secrets.DOCKER_TOKEN}}
#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with: 
#           push: true
#           tag: ramalakshmi79/demo:newnginx-image
#       - name: Ec2 connect
#         env:
#           PRIVATE_KEY: ${{ secrets.EC2_PEMKEY }}
#           HOSTNAME: ${{secrets.EC2_HOSTNAME}}
#           USER_NAME: ${{secrets.EC2_USERNAME}}
#         run: |
#          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
#          ssh -o SrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
#             sudo docker login -u ramalakshmi79 -p dckr_pat_nU7IyOT8C6mnnwOH9KNS9_Wi4IY
#             sudo docker pull  ramalakshmi79/demo:newnginx-image
#             sudo docker run -d -p 889:80 ramalakshmi79/demo:newnginx-image
#             '
       
       
